### ISSUE TITLE
JIDtoID

### ISSUE THREAD

**Issue by kaminoo** [hidespb/node-whatsapi#101]
Hey guys.
In the extensions for processNode there's a function JIDtoId that turns a groupId from JID to a simple Id.
There's cases which this is really annoying and should be up to the user to see if we want to use the complete JID or not. But we don't get the chance since the info gets lost.

Any chance you can remove that function and leave the complete JID there as it is in every other method?

Thanks!

**Comment by matteocontrini** [comment]
That was changed after #37 for consistency. WhatsApp nodes sometimes give JIDs, sometimes group IDs. We couldn't give you sometimes a JID and sometimes an ID, so the easiest way to fix this was truncate everything after the `@`, giving *always* an ID to the user.

If you need the ID, you can simply append `@g.us`, or `'@' + wa.config.gserver`. but I'm sure you already know this.

Does this make more sense now? Feel free to create a pull request with a new config option.

**Comment by kaminoo** [comment]
Thanks for the quick reply.
I had that work around in place.
I'll keep it then :)
