### ISSUE TITLE
Cannot send UTF8 character

### ISSUE THREAD

**Issue by hungchai** [hidespb/node-whatsapi#14]
When I try to send UTF8 character,such as "台灣", the received message will be blank, 

But When I try to send "台灣台灣台灣" in one message, I can receive "台灣" from whatsapp.

I have tried to change the raw text length method into bytelength, but it made other unknown error.

  Writer.prototype.getRawBufferLength = function(raw) {

    if (typeof raw == 'string')
    {
        var size = buffer.Buffer.byteLength(raw,'utf8') + 2;
    }
    else
    {
        var size = raw.length + 2;
    }

	return raw.length >= 0x100 ? size + 2 : size;
    };

Please advise on it

**Comment by hungchai** [comment]
@thiagupct I have made a pull request 2 weeks ago, what 's the progress now?

**Comment by thiagupct** [comment]
@hungchai : As like you, am too waiting for @hidespb to merge the PR or let us know why the PR is in hold.
