### ISSUE TITLE
Support for chat groups

### ISSUE THREAD

**Issue by tvandergeer** [hidespb/node-whatsapi#15]
Do you have any plans on supporting chat groups? It looks pretty straight forward to support this. If you like I can give it a try...

**Comment by hungchai** [comment]
but node-whatsapi still have not function to create / list group id?

**Comment by matteocontrini** [comment]
Can you stop writing the same message on multiple issues, please? We read them. This issue is still open and there's another one with the status of the work on WAUTH-2 and WA 1.5 (new dictionary/features). Just wait and fork and help, if you want.

**Comment by hungchai** [comment]
@matteocontrini, Sorry , I dont notice the issues is closed, so i rewrite a new one

**Comment by matteocontrini** [comment]
Main features for groups should be now working on the [branch](https://github.com/hidespb/node-whatsapi/tree/WAUTH-2_and_WA1.5)

**Comment by tvandergeer** [comment]
Thanks Matteo! Let's close this issue
