### ISSUE TITLE
basic doc/example code

### ISSUE THREAD

**Issue by gt584** [hidespb/node-whatsapi#2]
this project looks very exciting! any chance you could post same basic doc/examples for usage? thanks!

**Comment by hungchai** [comment]
hi @thiagupct, do you have example to demo sending the group message

**Comment by matteocontrini** [comment]
Hi,
you can just use the `sendMessage` function, passing the group id as the `parameter`.

**Comment by hungchai** [comment]
but node-whatsapi still have not function to create / list group id?

**Comment by matteocontrini** [comment]
We will work on that too, if you want to contribute, feel free to fork and send a pull request.
