### ISSUE TITLE
How to sync contacts with this API?

### ISSUE THREAD

**Issue by saptarsibhowmick** [hidespb/node-whatsapi#20]

**Comment by matteocontrini** [comment]
It will be possible with WAUTH-2. We are working on it.

**Comment by thiagupct** [comment]
This should sync your contacts. Copy paste this to whatsapi.js until WAUTH-2 is implemented.
```javascript
WhatsApi.prototype.requestSync = function(msisdnList) {

	var contacts = [];
	for (var number in msisdnList){
		var contact = new protocol.Node('user', null, null, ('+' + msisdnList[number]));
		contacts.push(contact);
	}
	
	var attributes = {
		to    : this.selfAddress,
		type  : 'get',
		id    : this.nextMessageId('sendsync_'),
		xmlns : 'urn:xmpp:whatsapp:sync'
	};

	var attr = {
		mode    : 'full',
        context : 'registration',
        sid     : ''+((common.tstamp().toString() + 11644477200) * 10000000),
        index   : ''+0,
        last    : 'true'
	};

	var syncnode = new protocol.Node('sync', attr, contacts);

	var messageNode = new protocol.Node('iq', attributes, [syncnode]);
	
	this.sendNode(messageNode);
};
```

**Comment by matteocontrini** [comment]
**WhatsAPI request**

```
tx  <iq to="xxx@s.whatsapp.net" type="get" id="sendsync_-1420498248-1" xmlns="urn:xmpp:whatsapp:sync">
tx    <sync mode="full" context="registration" sid="130649754480000000" index="0" last="true">
tx      <user>+39xxx</user>
tx    </sync>
tx  </iq>
```

**WhatsAPI response**
```
rx  <iq from="xxx@s.whatsapp.net" id="sendsync_-1420498248-1" type="result">
rx    <sync index="0" sid="130649754480000000" last="true" wait="175882" version="1420498249860749">
rx      <in>
rx        <user jid="39xxx@s.whatsapp.net">+39xxx</user>
rx      </in>
rx    </sync>
rx  </iq>
```

**node-whatsapi request**
```
tx <iq to="xxx@s.whatsapp.net" type="get" id="sendsync_-1420498795-1" xmlns="urn:xmpp:whatsapp:sync">
tx   <sync mode="full" context="registration" sid="14321432728500000000" index="0" last="true">
tx     <user>+39xxx</user>
tx   </sync>
tx </iq>
```

**node-whatsapi response**
Nothing!

Same problem with `requestServicePricing`. It seems that `iq` nodes with generated message IDs (prefix `get_service_pricing_`, `sendSync_`) get stuck somewhere.

**Comment by matteocontrini** [comment]
I don't get any response. What do you get?

**Comment by thiagupct** [comment]
```javascript
WhatsApi.prototype.onTransportData = function(data) { 
    console.log(JSON.stringify(data));
    this.reader.appendInput(data); 

	while(true) { 
		var node = this.reader.nextNode(); 
		if(node === false) { 
			break; 
		} 
		if(node) { 
			this.processNode(node); 
		} 
	} 
}; 
```
Use this--> ``` requestServicePricing ``` is returning data but unable to parse. TOKEN ERROR: 252

But```sendSync``` and ```getStatus``` is getting no response. We are doing something wrong.

**Comment by matteocontrini** [comment]
The token problem has been solved yesterday #24

**Comment by thiagupct** [comment]
Sorry my mistake.

**Comment by saptarsibhowmick** [comment]
wa.on('login', function(){
    console.log("Logged in to WA Server");
    requestSync("91xxxxxxxxxxx");
});

This keeps Logging in and Connecting continuously. This might be a silly question but I am new to nodejs. So whats the best way to sync a number and get the result that whether it exists or not in the console?

**Comment by thiagupct** [comment]
Sorry @saptarsibhowmick, the ```requestSync``` function is broken. We are getting no response from WA Server. A fix will be provided very soon.

Check [this](https://github.com/hidespb/node-whatsapi/issues/23) for the list of functions and their status which is in development.  Feel free to do your own research

**Comment by saptarsibhowmick** [comment]
@thiagupct Thank You. Looking forward to the fix.

**Comment by tvandergeer** [comment]
Try again with latest commit. It now works on my machine.

```
tx <iq to="xxx@s.whatsapp.net" type="get" id="sendsync_-1420626290-2" xmlns="urn:xmpp:whatsapp:sync">
tx   <sync mode="full" context="registration" sid="130651034900000000" index="0" last="true">
tx     <user>12 data length</user>
tx   </sync>
tx </iq>
```

```
rx <iq from="s.whatsapp.net" id="sendsync_-1420626290-2" type="result">
rx   <sync index="0" sid="130651034900000000" last="true" wait="172096" version="1420618854454874">
rx     <in>
rx       <user jid="s.whatsapp.net">12 data length</user>
rx     </in>
rx   </sync>
rx </iq>
```

**Comment by thiagupct** [comment]
:+1:  @tvandergeer Please check with ```mode : 'delta', context : 'background'``` too. Have a look at [this](https://github.com/mgp25/WhatsAPI-Official/wiki/Sync)

**Comment by tvandergeer** [comment]
Seems to be working too:
```
tx <iq to="xxx@s.whatsapp.net" type="get" id="sendsync_-1420628248-1" xmlns="urn:xmpp:whatsapp:sync">
tx   <sync mode="delta" context="background" sid="130651054480000000" index="0" last="true">
tx     <user>12 data length</user>
tx   </sync>
tx </iq>
```
```
rx <iq from="s.whatsapp.net" id="sendsync_-1420628248-1" type="result">
rx   <sync index="0" sid="130651054480000000" last="true" version="1420618854454874">
rx     <in>
rx       <user jid="s.whatsapp.net">12 data length</user>
rx     </in>
rx   </sync>
rx </iq>
```

Is there anything specific I should look at?

**Comment by saptarsibhowmick** [comment]
wa.requestContactsSync('91xxxxxxxxxx', 'delta', 'background'); 

should I use like this?

**Comment by thiagupct** [comment]
Just to ensure whether the ```mode : 'delta', context : 'background' ``` is setting a backoff time like it does with ```mode : 'full', context : 'registration' ```

```<sync index="0" sid="130651034900000000" last="true" wait="172096" version="1420618854454874">```

But wasn't!!

**Comment by tvandergeer** [comment]
@saptarsibhowmick Make sure the first argument is an array. Like this:
```
wa.requestContactsSync(['91xxxxxxxxxx'], 'delta', 'background');
```

**Comment by matteocontrini** [comment]
Fully working with my last commit https://github.com/hidespb/node-whatsapi/commit/dda23e6d7d8ba811f74c3fe521c9c146199aa7b5

**Comment by matteocontrini** [comment]
Array type for the first parameter is no longer a requirement
