### ISSUE TITLE
can not receive message.

### ISSUE THREAD

**Issue by mukedian0** [hidespb/node-whatsapi#28]
Hi,
The sample code of  receive message as below:
wa.on('message', function(from, id, name, body, author){
	   console.log("Message: receive");//+body+" From: "+from+" Name: "+name);
	});

The 'message' event not be triggered, and I didn't find the code of emit 'message' event at whatsapp.js.

**Comment by matteocontrini** [comment]
Which branch are you using?

--
Matteo
Inviato da Windows Phone

----- Messaggio originale -----
Da: "Jerry Huang" <notifications@github.com>
Inviato: ‎15/‎01/‎2015 11:25
A: "hidespb/node-whatsapi" <node-whatsapi@noreply.github.com>
Oggetto: [node-whatsapi] can not receive message. (#28)

Hi,
The sample code of receive message as below:
wa.on('message', function(from, id, name, body, author){
console.log("Message: receive");//+body+" From: "+from+" Name: "+name);
});
The 'message' event not be triggered, and I didn't find the code of emit 'message' event at whatsapp.js.

**Comment by mukedian0** [comment]
I downloaded the zip source code from https://github.com/hidespb/node-whatsapi.

**Comment by thiagupct** [comment]
Was the other functions working for you? 

The 'message' event is emitted from processors.js.

**Comment by matteocontrini** [comment]
Can you try enabling the debug option on `createAdapter` and post the output?

**Comment by mukedian0** [comment]
@thiagupct: Yes, the other functions work fine. I can send message, receive typing status and so on.

@matteocontrini: Please find the log in attachment.
![log](https://cloud.githubusercontent.com/assets/10543374/5770399/c14b466a-9d64-11e4-8f33-20a804cf18d9.jpg)


Thanks.

**Comment by mukedian0** [comment]
@thiagupct, @matteocontrini 

I think I have found the root cause.

The Text.match() function return false when receiving text messages. That is because the 'body' node does not exist. Below is the log:

console.log(node.child('notify'))
{ contents:
   { tag: 'notify',
     attributes: { xmlns: 'urn:xmpp:whatsapp', name: 'jerry' },
     children: [],
     data: '' } }

console.log(node.child('body'));
null;

**Comment by matteocontrini** [comment]
The body node doesn't exist because the message is encrypted. That shouldn't happen on the main branch, TBH.
The encryption problem is something we are planning to support in the new version implementation (WAUTH-2 branch)

**Comment by mukedian0** [comment]
Is there anything else I need to check? I currently use the master branch, and followed the sample form https://github.com/hidespb/node-whatsapi/wiki/Documentation.

**Comment by tvandergeer** [comment]
Is it possible for you to re-register/authenticate the phone number using Yowsup or WhatsAPI? I suspect that the WA platform has some setting (key?) stored for your account that the client you use can receive encrypted messages.

**Comment by matteocontrini** [comment]
How have you registered the number with WhatsApp?

--
Matteo
Inviato da Windows Phone

----- Messaggio originale -----
Da: "Jerry Huang" <notifications@github.com>
Inviato: ‎16/‎01/‎2015 08:46
A: "hidespb/node-whatsapi" <node-whatsapi@noreply.github.com>
Cc: "Matteo Contrini" <m.contrini@gmail.com>
Oggetto: Re: [node-whatsapi] can not receive message. (#28)

Is there anything else I need to check? I currently use the master branch, and followed the sample form https://github.com/hidespb/node-whatsapi/wiki/Documentation.

**Comment by mukedian0** [comment]
Sorry for my late response.
I just installed the whatsapp apk from Google Play, and  registered with my phone number, and entered the verification code, then I can normally use it to chat with my contacts.

**Comment by matteocontrini** [comment]
Right now you can't use a phone number registered on an Android phone with the API. The process on the device enables end-to-end encryption, something that's not yet handled.
If you want to use that number, you need to register it with the API (yowsup), but you won't be able to use it on your real phone.

**Comment by mukedian0** [comment]
Thanks, matteocontrini.

I think I have some misunderstanding. I want to implement a web whatsapp, then I can send/receive messages on PC side with the same account I registered on my phone if my phone is not around. Per your reply, It seems whatsapi can't implement this requirement right now, right?

**Comment by matteocontrini** [comment]
Right now, you can't
