### ISSUE TITLE
Out of service. Today 23 jan.

### ISSUE THREAD

**Issue by rodrigofaillace** [hidespb/node-whatsapi#30]
Hello Sir.

My node-whatsapi stopped working. Error while logging (auth).

Are you having the same problem?

Thanks,

**Comment by matteocontrini** [comment]
Are you getting a "not-authorized" error message if you enable debug?

**Comment by alamcordeiro** [comment]
Problem with WAUTH 1.0

I'm solved login updating dependency in package.json:
  "node-whatsapi": "hidespb/node-whatsapi#WAUTH-2_and_WA1.5" 
and run > npm update

But not receive event, message  or receivedMessage  (from WAUTH 2.0)

**Comment by alamcordeiro** [comment]
Parameter node on Text.prototype.process  (processors.js)
return no encrypted message on groups and encrypted message on privates message.

**Comment by matteocontrini** [comment]
If you register the number with yowsup or WhatsAPI, you won't get encryptes messages.
The WAUTH-2 branch is still in development: event names can change [at any time](https://github.com/hidespb/node-whatsapi/issues/23).

**Comment by alamcordeiro** [comment]
Exactly, thanks.
And number registered on WART ?

**Comment by matteocontrini** [comment]
The same thing applies. From what we've understood, only numbers registered with the latest Android version receive encrypted messages.
If you register the number with any other OS or API wrapper, that's ok.

**Comment by rodrigofaillace** [comment]
I am registering there (at whatsapi, from mgp25)....  using RegisterTool.php...  but no big deal till now (while auth in node)... it has stopped exactly today. The other number I have that was logged yesterday and didn´t disconnect till now, keep on working.

Matteo, about Debug, does this text below helps?

Thank you all for that fast feedback.


PS C:\nodejs\node_modules\whatsapi> node debug wa
< debugger listening on port 5858
connecting... ok
break in C:\nodejs\node_modules\whatsapi\wa.js:1
  1 var common = require('./whatsapi');
  2 var events = require('events');
  3 var util = require('util');
debug> c
< Connected to WA Server
< events.js:74
<         throw TypeError('Uncaught, unspecified "error" event.');
<               ^
< TypeError: Uncaught, unspecified "error" event.
<     at TypeError (<anonymous>)
<     at WhatsApi.emit (events.js:74:15)
<     at WhatsApi.processNode (C:\nodejs\node_modules\whatsapi\whatsapi.js:520:8)
<     at WhatsApi.onTransportData (C:\nodejs\node_modules\whatsapi\whatsapi.js:989:9)
<     at Socket.connect (C:\nodejs\node_modules\whatsapi\transport.js:26:52)
<     at Socket.emit (events.js:95:17)
<     at Socket.<anonymous> (_stream_readable.js:765:14)
<     at Socket.emit (events.js:92:17)
<     at emitReadable_ (_stream_readable.js:427:10)
<     at emitReadable (_stream_readable.js:423:5)

**Comment by matteocontrini** [comment]
If you don't restart the script, you won't have problems since it's a pre-login check that's causing the issue.
Try enabling debug mode (second parameter on `createAdapter`) and post the output.

**Comment by rodrigofaillace** [comment]
Thanks for createAdapter debug tip...

Connected to WA Server

tx <stream:features>
tx   <receipt_acks></receipt_acks>
tx   <status></status>
tx </stream:features>

tx <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="WAUTH-1" user="5521999999999">??M??b:?0    ?;????→???O→↑???
???)??N?t?x<(?~??(?yl??P???????;h?1?|0?f??xGG??'J?B/??????▲c??<?*?↑[???3q</auth>

rx <start from="s.whatsapp.net"></start>

rx <stream:features>
rx   <receipt_acks></receipt_acks>
rx   <w:profile:picture type="all"></w:profile:picture>
rx </stream:features>

rx <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">??_?
Qk?u+[?▼~?S?▼?</challenge>

tx <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">?e▼|?O>vr%=$??R?
?☼???????♫??????E.@???"4d-</response>

rx <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
rx   <not-authorized></not-authorized>
rx </failure>

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^

**Comment by rodrigofaillace** [comment]
(for best viewing, in the debug result above I´ve inserted a blank after the "<" ) Sorry.

**Comment by matteocontrini** [comment]
You have [markdown](https://guides.github.com/features/mastering-markdown/) for code escaping.

Anyway, that's the problem I had earlier too. If you really need the API to work, right now what you can do is cloning the repository, switching to the WAUTH-2 branch and using that code.

**Comment by migueltarga** [comment]
In this new repository, I am not able to get "private" messages (one to one)
only group messages, the current project is not emitting the receivetMessage.

**Comment by matteocontrini** [comment]
The event is called `receivedMessage` and [it is emitted](https://github.com/hidespb/node-whatsapi/blob/WAUTH-2_and_WA1.5/processors.js#L37) when a non-encrypted message is received.
For the encrypted messages problem, the solution is in the previous comments.

**Comment by rodrigofaillace** [comment]
Thank you Matteo. I really would like to thank all your effort and support. I am at migueltarga point right now...   just checking now the previous comments to receive encrypted....

**Comment by migueltarga** [comment]
@matteocontrini Thank you for all! Your are doing a great job!

**Comment by matteocontrini** [comment]
It's not just me :smile: There's @tvandergeer and @thiagupct too ;)

**Comment by rodrigofaillace** [comment]
Sorry to bother you again. 
I have just re-registered and all I receive is a < body> 3 data length < /body>

Inside that branch we have:

	host           : 'c.whatsapp.net',
	server         : 's.whatsapp.net',
	gserver        : 'g.us',
	port           : 443,
	device_type    : 'Android',
	app_version    : '2.11.473',
	ua             : 'WhatsApp/2.11.473 Android/4.3 Device/GalaxyS3',

Do I have to change to Nokia302 (I have tried both, without success)?

**Comment by matteocontrini** [comment]
Is the `receivedMessage` event called? Note that there's just one parameters in v0.2.
If you get that body node with 3 characters inside, it means that you just got a non-encrypted message with a text of length 3. What's the problem you're having?

**Comment by rodrigofaillace** [comment]
Got now. That works! Thank you Sir.

It would be great if we have a "donate" button somewhere here..   I know it is not all about money, but I would be glad to pay you all a beer (it´s not much, and less than you deserve). :)  Cheers!

Thank you again..

**Comment by alamcordeiro** [comment]
@rodrigofaillace has re-registered using that application ?

**Comment by rodrigofaillace** [comment]
I´ve used RegisterTool.php from mgp25 whatsapi...

**Comment by iMicknl** [comment]
@matteocontrini >  "Is the receivedMessage event called? Note that there's just one parameter in v0.2.
If you get that body node with 3 characters inside, it means that you just got a non-encrypted message with a text of length 3. What's the problem you're having?"

Is it already possible to get encrypted messages with the WAUTH-2_and_WA1.5 branch? I am using a password generated on a real Android device, but I can't get it working yet.

**Comment by matteocontrini** [comment]
The solutions are two:
- registering the number again with the API
- changing device information, setting something that's not Android. I haven't tested this, you can take a look here and try https://github.com/mgp25/WhatsAPI-Official/commit/4576f4c9df7cc0f36053be94524ae5261490d22f

**Comment by matteocontrini** [comment]
This should work around the encryption issue https://github.com/hidespb/node-whatsapi/commit/193633f1798d01b9e43aa5e75436971f796d7524
Can anyone with that problem now check?

**Comment by alamcordeiro** [comment]
Nice.
Problem solved @matteocontrini
