### ISSUE TITLE
Error sending Image

### ISSUE THREAD

**Issue by humodev** [hidespb/node-whatsapi#31]
I'm getting this error while sending an image: [Error: Command failed: Parametro no valido: /media] timedOut: false, killed: false, code: 4, signal null

Any ideas?

**Comment by matteocontrini** [comment]
Can you post the code?

**Comment by humodev** [comment]
Yes of course!

var express = require('express');
var router = express.Router();
var types = require('../types.js');
var mimetypes = require('../mimetypes.js');

//whatsapi
var common = require('whatsapi');
var events = require('events');
var util = require('util');

var wa = new common.createAdapter();
util.inherits(wa, events.EventEmitter);


//Config change in the object in order to send with the corresponding number
//Has to be configured on the mysql db
wa.defaultConfig.msisdn = "59896725386";
wa.defaultConfig.username = "59896725386";
wa.defaultConfig.password = "hx2LcvXWxc+3JAKp8NTN8txmv/I=";
wa.defaultConfig.ccode = "598";


router.route('/')

	//send multiple/single text message
	.post(function(req,res){
		//Received type of message 
		var msgtype = req.body.type;

wa.connect();

		//Wait for connection event and the login to WA Server
		wa.on('connect', function(){
			wa.login(); 
		});


		//Send online to WA server
		wa.on('login',function(){
			wa.sendIsOnline(); //You will be online now
			var idMessage = wa.nextMessageId('message');

			switch(msgtype){
				case types.TEXT:
					wa.sendMessage(req.body.target, req.body.text, idMessage);
					break;
				case types.IMAGE:
					if(!req.body.url){
						wa.disconnect();
						res.json("empty url of image");
					}

					var ArrUrl = req.body.url.split('.');
					var ext = ArrUrl[ArrUrl.length-1];

					if(ext!=mimetypes.JPEG && ext!=mimetypes.PNG && ext!=mimetypes.GIF){
						wa.disconnect();
						res.json("incorrect image mime type");
					}
					
					wa.sendImage(req.body.target, req.body.url, req.body.text);
					break;
				case types.AUDIO:
					if(!req.body.url){
						wa.disconnect();
						res.json("empty url of audio");
					}

					var ArrUrl = req.body.url.split('.');
					var ext = ArrUrl[ArrUrl.length-1];

					if(ext!=mimetypes.MP3 && ext!=mimetypes.WAV && ext!=mimetypes.WMA){
						wa.disconnect();
						res.json("incorrect audio mime type");
					}

					wa.sendAudio(req.body.target, req.body.url, idMessage);
					break;
				case types.VIDEO:
					if(!req.body.url){
						wa.disconnect();
						res.json("empty url of video");
					}

					var ArrUrl = req.body.url.split('.');
					var ext = ArrUrl[ArrUrl.length-1];

					if(ext!=mimetypes.AVI && ext!=mimetypes.MP4 && ext!=mimetypes.MOV && ext!=mimetypes.GP){
						wa.disconnect();
						res.json("incorrect video mime type");
					}

					wa.sendVideo(req.body.target, req.body.url, req.body.text, idMessage);
					break;
				default: 
					wa.disconnect();
					res.json("wrong type");
			}

			i++;
		});
wa.on('serverReceived', function(from, id, type, time){
                                   wa.disconnect();
				res.json("success");
});

		wa.on('error', function(err){
			console.log('--' + err + '--');
			wa.disconnect();
			res.json("Error:" + err);
		});

		wa.on('mediaError', function(err){
			console.log(err);
			wa.disconnect();
			res.json("Media Error:" + err);
		});


		wa.on('connectError', function(err){
			console.log('--CE--' + err + '--');
			wa.disconnect();
			res.json('Connection error:' + err);
		});


	});
module.exports = router;

**Comment by matteocontrini** [comment]
I meant the relevant code for the question, not the whole program with your number and the password.
**Where are you getting the error** and what are you trying to do? What you posted in the original post doesn't seem to be related to node-whatsapi directly (Spanish error message?!).

**Comment by humodev** [comment]
The error appears here

    wa.on('mediaError', function(err){
        console.log(err);
        wa.disconnect();
        res.json("Media Error:" + err);
    });

When i'm trying to do this: 

wa.sendImage(req.body.target, req.body.url, req.body.text);

**Comment by matteocontrini** [comment]
1) are you using the WAUTH-2 branch?
2) do you have the ImageMagick dependency installed on your system? (the npm module is not enough)
3) there probably is something wrong with the parameter. Can you enable debug mode and see what gets sent? Also, check that you're using correctly the parameters because I don't know what `req.body.url` is for example. [WAUTH-2 jsdoc for `sendImage`](https://github.com/hidespb/node-whatsapi/blob/WAUTH-2_and_WA1.5/whatsapi.js#L269)

**Comment by humodev** [comment]
I'm using WAUTH-2 branch, and the parameters i'm sending seem to be correct. What I don't have is the ImageMagick dependency installed!
I'm going to try that, thank you very much for your time. 

I let you know if that solves it.

**Comment by matteocontrini** [comment]
Anyway the problem seems to be even before resizing and sending the image. The process *probably* gets stuck somewhere in `getMediaFile`, called internally, which tries to find the resource to be sent. Please check again which parameters you are passing to the `sendImage` function, and post them here.

**Comment by humodev** [comment]
This is what i get from the debug



tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>

tx <auth mechanism="WAUTH-2" user="59896725386">104 data length</auth>

rx <start from="s.whatsapp.net"></start>

rx <stream:features></stream:features>

rx <challenge>20 data length</challenge>

tx <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">35 data length</response>

rx <success t="1427818264" props="4" kind="free" status="active" creation="14266
88920" expiration="1458224920">20 data length</success>

tx <presence name="59896725386"></presence>

rx <ib from="s.whatsapp.net">
rx   <offline count="0"></offline>
rx </ib>

rx <presence from="59896725386@s.whatsapp.net"></presence>

tx <iq id="upload-1427818170-2" to="s.whatsapp.net" type="set" xmlns="w:m">
tx   <media hash="so32MEup8cj1zmrbRAzh1f0OP6oAME9J5j/hae05df0=" type="image" siz
e="48764"></media>
tx </iq>

rx <iq from="s.whatsapp.net" id="upload-1427818170-2" type="result">
rx   <duplicate url="https://mmi120.whatsapp.net/d/Alqdfmd31l-cwgQjchcCr9XbFEgTm
0Vp57n2uu8kIWGT.jpg" size="48764" mimetype="image/jpeg" filehash="so32MEup8cj1zm
rbRAzh1f0OP6oAME9J5j/hae05df0=" type="image" width="1024" height="768"></duplica
te>
rx </iq>
{ [Error: Command failed: Par metro no v lido: /media
] timedOut: false, killed: false, code: 4, signal: null }




I'm using this function now to avoid problems. 

wa.sendImage('598**********', 'http://imagenesanimadas.co/wp-content/uploads/2011/08/paisajes_hermosos_del_mundo2.jpg', 'Hello');

**Comment by matteocontrini** [comment]
First, learn how to use markdown for posting code blocks (instead of removing syntax elements :neutral_face:), because that's unreadable.
Anyway, I managed to reproduce the error. It seems to be a Windows problem:
- when the image file is downloaded, the local generated path is wrong **if** you're using Windows. I'll try to fix this and push a commit ASAP
- Imagemagick on Windows requires an extra step. See [this](http://stackoverflow.com/a/11710210/1633924) reply (and comments) on StackOverflow for help. I will try to move to a more updated image library that doesn't require external dependencies. [`lwip`](https://github.com/EyalAr/lwip) is promising.

**Comment by humodev** [comment]
Yeah, sorry about that. It's my first time asking something, anywhere. I always find the answers but I didn't this time.
Thank you very much for your help.

**Comment by matteocontrini** [comment]
The latest commit fixes the issue.
What you need to do is [install ImageMagick](http://www.imagemagick.org/script/binary-releases.php#windows) and **restart Windows**. This step is important. After that, the script should work.
