### ISSUE TITLE
Unable to get groupId in ChangeGroupParticipants

### ISSUE THREAD

**Issue by amozgachev** [hidespb/node-whatsapi#33]
Hello.

My application operates with several groups. So I need to watch over participants.
But in ChangeGroupParticipants I can't get groupId to know, in which one users were added or left.

Here is the code:
https://github.com/hidespb/node-whatsapi/blob/WAUTH-2_and_WA1.5/whatsapi.js#L1281-L1302

Also there is a naming error in emitted event.

Thanks.

**Comment by matteocontrini** [comment]
Hi,
thanks for bringing this to our attention. I will commit an update later, switching to the new callback communication approach. I will remove the event and you'll be able to get responses from the server when you call `changeGroupParticipants` using a simple callback.

Note that the `groupChangedParticipants` is called only when you make a change on the group, and not when someone other makes it. An event will be added for this in a future version.

Finally, which "naming problem" are you talking about?

**Comment by amozgachev** [comment]
Hi.

Thanks for your answer.

Is there a way to get noticed if someone other is left?

Naming problem:
changedGroupParticipants <-> groupChangedParticipants

**Comment by matteocontrini** [comment]
I think I chose that name for consistency between group events. So that every event related to groups starts with the `group` keyword.
If you enable debug mode, you'll see that when someone leaves the group, you get a `notification` node about that. I'll try setting up an event for that kind of notification as soon as I can...

**Comment by amozgachev** [comment]
Ok. But in comment I can see:
* @event changedGroupParticipants

Thanks.
I'm waiting for notifications primary.

**Comment by matteocontrini** [comment]
https://github.com/hidespb/node-whatsapi/commit/076bea9db3e15fe384e5f3856c91b0e238f6c45d

New events:
* `notificationGroupCreated`
* `notificationGroupParticipantsChanged`
* `notificationGroupSubjectChanged`

I'll close this issue when the new group management functions with callbacks are ready.

**Comment by amozgachev** [comment]
Thanks.

I'll check it soon in my project.

**Comment by amozgachev** [comment]
Events work perfectly.

Thanks.
