### ISSUE TITLE
Callbacks are not using node.js style

### ISSUE THREAD

**Issue by amozgachev** [hidespb/node-whatsapi#34]
Hi.

As I see, you are going to make callbacks for all request-methods.
It's much better than events to work with.

But why are you using basic callbacks?
In node style `(err,res)->` it's easier to handle not only result but errors too.

Thanks.

ps Promises are also good ;)

**Comment by matteocontrini** [comment]
Hi,
Thanks for the suggestion. The fact is that request to WhatsApp rarely fail, so I didn't even know how an error response looks like.
I've managed to reproduce an error response, I will try handling them with callbacks later today.

Thanks for pointing that out :)
And I will look into promises to...
This issue will be closed when I commit changes.

**Comment by amozgachev** [comment]
Hi.

For example, to get error you can send incorrect password while logging in - you'll get 'not-authorized' error event.
You'll also get this error if you are blocked.

**Comment by matteocontrini** [comment]
Connection/authentication callbacks already have a error parameter.
The others should as well now. I will update the documentation accordingly.

Thanks for the suggestion, I had missed that :smile:

**Comment by matteocontrini** [comment]
Docs: https://github.com/hidespb/node-whatsapi/wiki/Error-handling
