### ISSUE TITLE
Sometimes IDs and sometimes JIDs for groups

### ISSUE THREAD

**Issue by amozgachev** [hidespb/node-whatsapi#37]
Hi.

While using `whatsapi` I've found out that in some cases for groups you return ids (`groupInfo`, `notificationGroupParticipantsChanged`, ...) and in other cases you return jids (`groupLeave`, ...).

It'll be good to choose one of them and use as unique id in all cases.

Thanks.

**Comment by matteocontrini** [comment]
That's what WhatsApp returns, I can't do much.
If you need consistency, you can always use the ID:

```javascript
var idOnly = idOrJid.split('@')[0];
```

**Comment by amozgachev** [comment]
Yes. I'm doing it this way.

Close this issue if you don't want to deal with it.

Thanks.

**Comment by amozgachev** [comment]
Hi again.

I've found a good example:

In group events in `groupId` field id is returned.
In group notifications in `groupId` field jid is returned.

This makes me crazy.

Thanks.

**Comment by matteocontrini** [comment]
Thanks for the example.
I ask you a bit more patience, I plan to review the groups methods and rewrite them with callbacks this week.

**Comment by amozgachev** [comment]
Thanks a lot.
