### ISSUE TITLE
Rate-limit option needed

### ISSUE THREAD

**Issue by amozgachev** [hidespb/node-whatsapi#38]
Hi.

If you send messages too frequently there is a great chance to get blocked.
What about adding option into config to make delay between queries  like in https://github.com/SGrondin/bottleneck?

Thanks.

**Comment by matteocontrini** [comment]
If you send messages too frequently, you are probably using the API irregularly and/or for spamming.
Use the API as you would normally use a WhatsApp client and you won't get blocked.

There is no need to introduce rate limiting, as you don't risk anything if you use the API regularly. If you don't, we do not offer support and you'll need to implement limits on your side.

Thank you.

**Comment by amozgachev** [comment]
I understand you.

But in my case I only interacts with many groups\users in the same time.
There is no spam, no identical messages - just frequency.

I'll use bottleneck.

Anyway, thank you for your answer.
