### ISSUE TITLE
Util in extensions

### ISSUE THREAD

**Issue by amozgachev** [hidespb/node-whatsapi#39]
Hi.

Util is not required in extensions!

**Comment by matteocontrini** [comment]
Can you elaborate more? I don't get what you mean...

**Comment by amozgachev** [comment]
In latest version `/extensions` folder throws exception as it uses `util` but `require('util')` is missed.

**Comment by matteocontrini** [comment]
Ops, I missed that. Fixed.
Thank you!

**Comment by amozgachev** [comment]
Not only `account` - check all dependenсies.

**Comment by amozgachev** [comment]
Also `common.js` in `account`

**Comment by matteocontrini** [comment]
Make a pull request if you want, I won't be able to fix this today. I don't want to make mistakes again doing things fast :)

**Comment by amozgachev** [comment]
Also `util` in `groups`.

**Comment by humodev** [comment]
Also mime in media.js

**Comment by matteocontrini** [comment]
You can do that yourself and create a pull request.

**Comment by humodev** [comment]
Yes I solved it, I commented here so that other people with the same error, and you know about this.
Mainly to keep everything in the same issue! 
Thank you

**Comment by matteocontrini** [comment]
Ok.
Thank you for all the reports about missing requires. Unfortunately I haven't had time to look at all the files in detail or try all the functions, so I prefered to push what I had, even with errors...

Remember that the WAUTH-2 branch doesn't guarantee that the code is fully working.

**Comment by humodev** [comment]
Yes of course.
Your code works fine, has small fixable bugs. 
If I find anything else I let you know
Thank you very much.

**Comment by amozgachev** [comment]
Also found:
`fs` in `media`
`../MediaType.js` in `account`
