### ISSUE TITLE
Registration issue for india 

### ISSUE THREAD

**Issue by safiresh** [hidespb/node-whatsapi#40]
hi,
i always getting this error. kindly guide me whats wrong 

{ status: 'fail', reason: 'bad_token' } '{"status":"fail","reason":"bad_token"}\n'

**Comment by matteocontrini** [comment]
Which method are you using root registering?
There's a doc in the wiki about that

**Comment by safiresh** [comment]
// This is my code 

var common = require('whatsapi');
var config = {
    msisdn: '91XXXXXXXXXX',
    username: 'Sathish kumar',
    device_id: '355B756673A80D17',
    ccode: '91',
    reconnect: true,
    host: 'c2.whatsapp.net',
    server: 's.whatsapp.net',
    gserver: 'g.us',
    port: 443,
    device_type: 'S40-2.12.61',
    app_version: '2.12.61',
    ua: 'WhatsApp/2.12.61 S40/08.71 Device/NokiaX2-01',
    challenge_file: __dirname + '/challenge'
};
var wa = new common.createRegistration(config);
wa.requestCode();

**Comment by matteocontrini** [comment]
As stated in the documentation and in commits comments, registration through the Node.js API is not implemented.
Methods for getting a password are documented [here](https://github.com/hidespb/node-whatsapi/wiki/How-to-obtain-your-WhatsApp-password%3F)
