### ISSUE TITLE
send media url is not defined

### ISSUE THREAD

**Issue by humodev** [hidespb/node-whatsapi#42]
I'm getting this error in file media.js line 144 

ReferenceError: url is not defined. 
This is when I call the function wa.sendVideo(target, url, text, callback)

I'm running node on windows.

**Comment by humodev** [comment]
I solved it adding 

var url = require('url');
var fs = require('fs'); 

to media.js

thank you

**Comment by amozgachev** [comment]
https://github.com/hidespb/node-whatsapi/issues/39
