### ISSUE TITLE
readListSize error

### ISSUE THREAD

**Issue by eduardotang** [hidespb/node-whatsapi#47]
```javascript
/app/node_modules/whatsapi/protocol.js:522
        throw 'Invalid list size in readListSize: token: ' + token;
                                                           ^
Invalid list size in readListSize: token: 131
```

**Comment by matteocontrini** [comment]
Post the code and the debug log. What should I understand from that?

**Comment by eduardotang** [comment]
hey, sorry

This function is throwing the error when token is not 0, 0xF8 and 0xF9
so should it take care of some other values ??
so far i have experienced token = 131, 233


```javascript
Reader.prototype.readListSize = function(token) {
	if (token == 0) {
		return 0;
	};
	
	if (token == 0xF8) { // 248
		return this.readInt8();
	}

	if (token == 0xF9) { // 249
		return this.readInt16();
	}

	throw 'Invalid list size in readListSize: token: ' + token;
};
```

**Comment by matteocontrini** [comment]
I know which function is throwing, it's written in the stack trace.
The values you mentioned are invalid and they can't be handled.
I've asked you for the code of your application and the debug mode log, I need to know what requests you are doing and why you're getting an invalid response.

**Comment by eduardotang** [comment]
The application didn't do much,
I just connect and login , then start express, exposing a route to send message
so i make a request to the url and can successfully send message, then i basically left it on and it would get that invalid response a while later.

At first, i suspect what i was doing wrong is that i tried to do connect and login every hour.
but weird thing is that it got the invalid response within an hour, so i didnt think that is the problem.

At last, after i read your message,  I removed that part and ran it through debug mode, then it did not happen again (have run it for 12 hours already)

**Comment by matteocontrini** [comment]
When you send messages, do you have a queue for them? You can't send too many messages at the same time (irregular use) and that could cause something wrong in the stream.

**Comment by eduardotang** [comment]
so another day has gone, and it hasn't got that response, so you may close the issue first

**Comment by matteocontrini** [comment]
Ok, reopen the issue if you have the problem again.
And keep in mind the rate-limit/queue when sending many nodes.

**Comment by eduardotang** [comment]
yeah thx
