### ISSUE TITLE
Is it possible to sync messages that you received previously?

### ISSUE THREAD

**Issue by leschekfm** [hidespb/node-whatsapi#48]
Hi,
I'm not sure if it is possible to request messages that have been sent to your whatsapi instance previously.
My use case would be to rerequest a message if something failes while processing and storing it. 
I read the documentation but haven't found a function which would allow this. 
Does this mean that if you fail to persist a message it is gone forever?

Thanks for clarification :)

**Comment by matteocontrini** [comment]
No. Messages are stored on the server for 30 days OR until they are delivered to the client (that is when the `receipt` is sent). After that, it is your application's responsibility to keep track of the incoming messages.
This is the reason why official apps don't, unlike Telegram, roam messages between devices if you install the app on more than one of them.

Your application should be able to reliably cache the messages.
