### ISSUE TITLE
where is createRegistration?

### ISSUE THREAD

**Issue by Santinell** [hidespb/node-whatsapi#50]
Why exports.createRegistration is commented in whatsapi.js ?
If uncomment it i can register new account like in registerTool.php ? (https://github.com/mgp25/Chat-API)

**Comment by matteocontrini** [comment]
Registration is not implemented through this API and I don't know if it will. There's a page in the wiki explaining the different ways to get a password

**Comment by Santinell** [comment]
Yeah, I get password with registerTool.
But I need make it auto and not by PHP, so if its not implemented - maybe i can implement it make pull request?

**Comment by matteocontrini** [comment]
If you are able to, of course!
