### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by vcanilkumar** [hidespb/node-whatsapi#54]
Hi All,

I'm new to JS , failed to setup the project.
npm install whatsapi --save is not working

I have copied all the .JS files to my workspace and having the below code in my HTML

		var common=require('whatsapi');
		var events = require('events');
		var util = require('events');
			
		var wa = new common.createAdapter();
                 util.inherits(wa, events.EventEmitter);

		wa.connect(); 

		//Wait for connection event
		wa.on('connect', function(){
		    console.log("Connected to WA Server");
		    wa.login(); //Login function
		});

		//Wait for Login event
		wa.on('login', function(){
		    console.log("Logged in to WA Server");
		    //TODO: send composing/paused status
		    wa.sendIsOnline();
		    wa.sendMessage ("<,Num>>", "Test message using Node.js", null)  //sending message
		});

		wa.on('message.delivered', function(from, id, t){
		   console.log("Message received by:"+from);
		   //wa.disconnect();  //WA server connection will be disconnected
		});

		//Receive typing status
		wa.on('typing', function(from, tag){
		    console.log(from+"-"+tag);
		}); 

		//Event to receive and log messages
		wa.on('message', function(from, id, name, body, author){
		   console.log("Message: "+body+" From: "+from+" Name: "+name);
		});

I'm getting the below error

Uncaught Error: Module name "whatsapi" has not been loaded yet for context: _. Use require([])

I have tried using

require(['whatsapi'], function (foo) {
			 console.log("whatapi is loaded");
		});
but getting compilation error @ new common.createAdapter();

Could you please share any complete  working app ?

Thanks

**Comment by tvandergeer** [comment]
As far as I can see the problem is in the node-whatsapi that's not installed correctly (or not at all). Can you provide the output of 
```
npm install whatsapi --save
```

NB. There is at least one error in you code, but that's not causing your current issue.
```javascript
var events = require('events');
var util = require('events');
```
On the second line you probably want:
```javascript
var util = require('util');
```

**Comment by vcanilkumar** [comment]
Thanks for quick response

npm command output:

npm ERR! network tunneling socket could not be established, statusCode=400
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'


Other npm command works ...Ex : npm install mime .

Even I don't see events and util js files in the folders.


Regards, Anil

**Comment by tvandergeer** [comment]
You probably need to update your npm version. It's not a problem in node-whatsapi. See [here](https://github.com/npm/npm/issues/7925) for more info.

And regarding the util and events. These are built-in modules in node, but you need to "include" them whenever you use them just like external/installable modules.

**Comment by matteocontrini** [comment]
It seems to be an old issue reported [here](https://github.com/npm/npm/issues/6454) as well.
[Update npm](https://docs.npmjs.com/getting-started/installing-node)

And please follow the [Getting started](https://github.com/hidespb/node-whatsapi/wiki/Getting-started) guide, because the code you posted is a legacy code, it doesn't work that way anymore.
