### ISSUE TITLE
Whatsapi has an error after acouple of minutes (rx <stream:error> rx   <ack></ack> rx </stream:error>)

### ISSUE THREAD

**Issue by ExplodingCamera** [hidespb/node-whatsapi#55]
Yes, i have seen the old issue on here but i stil can't get it to work.
My Console Log: http://paste.explodingcamera.com/raw/ifajawurud
My code:

```js
var whatsapi = require('whatsapi');
var wa = whatsapi.createAdapter({
  msisdn         : 'xxx',
  password       : 'xxx=',
  username       : "xxxBot",
  ccode          : 'xxx',
}, true);
//Wait for connection event
wa.connect(function connected(err) {
    if (err) { console.log(err); return; }
    console.log('Connected');
    // Now login
    wa.login(logged);
});
function logged(err) {
    if (err) { console.log(err); return; }
    console.log('Logged in to WA server');
    wa.sendIsOnline();
    console.log("Auf Whatsapp online gegangen");
    wa.requestServerProperties(function gotProperties(err, props) {
        console.log("Properties wurden gesendet");
    });
    console.log("---------------------------------");
}
wa.on('receivedMessage', function(message) {
    console.log('Nachicht von '+message.from+': '+message.body);
    switch(message.body) {
        case "!menu":
                wa.sendMessage(message.from, "Commands: !menu, ...", function(err, id) {
                    if (err) { console.log(err.message); return; }
                    console.log('Server received message %s', id);
                });
                break;
    }
});
```

**Comment by matteocontrini** [comment]
Are you using the latest version available on npm?

**Comment by ExplodingCamera** [comment]
I've just updated to the latest version of node, npm and whatsapi and i'm still getting the same error after a couple of minutes.

**Comment by matteocontrini** [comment]
When you launch the application multiple times, are you seeing the same messages incoming more than once?

**Comment by ExplodingCamera** [comment]
i am getting

`tx <iq id="getproperties-1433175548-1" type="get" xmlns="w" to="s.whatsapp.net">`
`tx   <props></props>`
`tx </iq>`
`---------------------------------`
`rx <message from="4915257874155@s.whatsapp.net" id="message-1432391328-1" retry=   `                                                                                                                                                          `"3" offline="3" type="text" t="1432391328" notify="Henry's Bot">`
`rx   <body>Test message using Node.js</body>`
`rx </message>`

everytime i start

**Comment by matteocontrini** [comment]
Well, that problem should have been fixed. Are you immediately replying to the message after you get it? Can you try registering the phone number again? Sometimes an account can get stuck in that situation.

**Comment by ExplodingCamera** [comment]
Ok i'll try to register the number again.
