### ISSUE TITLE
Received Video Rotate

### ISSUE THREAD

**Issue by Danzed** [hidespb/node-whatsapi#56]
Hi.
I have the following problem. When I download  a video changes the rotation. some videos are upside down.
This is my code:

    wa.on('receivedVideo', function(video){
		console.log("Received video:\n", video);
	    fs.writeFile('media/imagesThumb/video-'+video.from+'-'+video.file+'-thumb.jpg', video.thumbData); 
	    wa.downloadMediaFile(video.url, function(err, path){
	    	if(err){
	      		console.log('error storing file: ' + err);
	    	}else{
				var newMessage = new received();		  	
			 	newMessage.from = video.from.substring(0,11);
			 	newMessage.body = path.substring(path.search('media')+6);
			 	newMessage.id = video.id;
				newMessage.date = video.date;
				newMessage.typeMsg = 'video';
				newMessage.save(function(err){
					if(err){
		            	throw new Error(err);
		            }
					io.sockets.emit('ReceivedMessage', {
			   			Message: newMessage
				   	});
				});
	      		console.log('file downloaded at: '+ path);
	    	}
	  	});
	});

**Comment by tvandergeer** [comment]
I think it depends on the video player you use to play the file. Some videos have an "orientation" flag which is not respected/used by some video players. Try playing back using QuickTime player or VLC. 




Best regards,




Tom van der Geer

**Comment by Danzed** [comment]
He injected into a website with angular inside `<video>` tag. I tested with windows media, windows media clasic and VLC It looks at all the same way

**Comment by matteocontrini** [comment]
This is not something related to our module, the message object you get is the raw data we parse from incoming nodes.

**Comment by tvandergeer** [comment]
Well... It's just the thumbnail we get from the message object. You have to download the video from a URL hosted bij WA. I see no possible reason why the video would loose it's orientation by downloading it...
