### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by JulianHH** [hidespb/node-whatsapi#57]
Hi there!

I extraced my Password using this method: https://github.com/mgp25/Chat-API/wiki/Extracting-password-from-device (android -> bash)

But I can't login. I enabled debug output and get this error:

Relying on plugins

```Connected

tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>

tx <auth mechanism="WAUTH-2" user="491xxx"></auth>

rx <start from="s.whatsapp.net"></start>

rx <stream:features></stream:features>

rx <challenge>�jV�F
                   0�L፳�����</challenge>

tx <response>Y�T��:n2g����I4�\�GF��:w3ۢx��!�N~</response>

rx <failure>
rx   <not-authorized></not-authorized>
rx </failure>

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at WhatsApiDebug.emit (events.js:74:15)
    at WhatsApiDebug.WhatsApi.processNode (/Users/jules/PhpstormProjects/storycaches/storycaches-base/node_modules/whatsapi/extensions/processNode.js:254:8)
    at WhatsApiDebug.processNode (/Users/jules/PhpstormProjects/storycaches/storycaches-base/node_modules/whatsapi/whatsapi.js:380:52)
    at WhatsApiDebug.WhatsApi.onTransportData (/Users/jules/PhpstormProjects/storycaches/storycaches-base/node_modules/whatsapi/whatsapi.js:357:9)
    at Socket.<anonymous> (/Users/jules/PhpstormProjects/storycaches/storycaches-base/node_modules/whatsapi/transport.js:26:52)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
```

Anyone experiencing the same issues?

Thanks in advance!

Best,
Julian

**Comment by tvandergeer** [comment]
Can you post the output again, but his time make sure that all information
is visible in your message. All <tags> got lost.
Thanks,

Tom 

Van:  JulianHH <notifications@github.com>
Beantwoorden - Aan:  hidespb/node-whatsapi
<reply+0015f894a6428f27624f4f53212064f5158d42df35ed76ac92cf00000001117e7b049
2a169ce04e007e1@reply.github.com>
Datum:  Thursday 28 May 2015 08:43
Aan:  hidespb/node-whatsapi <node-whatsapi@noreply.github.com>
Onderwerp:  [node-whatsapi] Can't login (#57)


Hi there!

I extraced my Password using this method:
https://github.com/mgp25/Chat-API/wiki/Extracting-password-from-device
(android -> bash)

But I can't login. I enabled debug output and get this error:
> 
> Connected
> 
> tx stream:features
> tx   
> tx   
> tx   
> tx   
> tx /stream:features
> 
> tx 
> 
> rx 
> 
> rx stream:features/stream:features
> 
> rx i��ڊ�Z�~r
> ���
> 蒙
> 
> tx N���i7
> �
> x��Ҋ�����6F��A��-�z*<:
> 
> rx 
> rx   
> rx 
> 
> events.js:74
>  throw TypeError('Uncaught, unspecified "error" event.');
>  ^
> TypeError: Uncaught, unspecified "error" event.
>  at TypeError ()
>  at WhatsApiDebug.emit (events.js:74:15)
>  at WhatsApiDebug.WhatsApi.processNode
> >(/Users/julian.gner/PhpstormProjects/storycaches/storycaches-base/node_module
> s/whatsapi/extensions/processNode.js:254:8)
>  at WhatsApiDebug.processNode
> (/Users/julian.ner/PhpstormProjects/storycaches/storycaches-base/node_modules/
> whatsapi/whatsapi.js:380:52)
>  at WhatsApiDebug.WhatsApi.onTransportData
> (/Users/julian.gner/PhpstormProjects/storycaches/storycaches-base/node_modules
> /whatsapi/whatsapi.js:357:9)
>  at Socket. 
> (/Users/julian.ner/PhpstormProjects/storycaches/storycaches-base/node_modules/
> whatsapi/transport.js:26:52)
>  at Socket.emit (events.js:95:17)
>  at Socket. (stream_readable.js:764:14)
>  at Socket.emit (events.js:92:17)
>  at emitReadable (_stream_readable.js:426:10)

Anyone experiencing the same issues?

Thanks in advance!

Best,
Julian

—
Reply to this email directly or view it on GitHub
<https://github.com/hidespb/node-whatsapi/issues/57> .

**Comment by matteocontrini** [comment]
@tvandergeer edit the first message and you'll find the original output. It just isn't escaped

**Comment by JulianHH** [comment]
I updated my post also :)

**Comment by matteocontrini** [comment]
Not authorized probably means that you've been temporarily blocked. Not related to our module.

**Comment by JulianHH** [comment]
Hmm. may be! But I can still login via usual whatsapp app and can chat with other people.

Is there any way to better debug this? Or any hints what I can try?

**Comment by matteocontrini** [comment]
Make sure the mobile app is completely killed

**Comment by JulianHH** [comment]
The phone is switched off :)

**Comment by tvandergeer** [comment]
Maybe you have the incorrect password. When I did it I followed [this procedure](https://github.com/hidespb/node-whatsapi/wiki/How-to-obtain-your-WhatsApp-password), which uses another App (See method 3 "On Android").

**Comment by JulianHH** [comment]
I tried that method too, but it says

> Couldn't read whatsapp files, are you root? 

And it asked for root before that, which I of course accepted.

**Comment by matteocontrini** [comment]
You must gain root access before using that method

**Comment by JulianHH** [comment]
Yeah, that's what I meant with "And it asked for root before that, which I of course accepted."

I obtained root.

**Comment by matteocontrini** [comment]
Are you having the same issue? Can you try logging in with yowsup or Chat-API to see if the problem is the password itself or something else?

Thanks

**Comment by JulianHH** [comment]
Hmm. Thanks for pointing into this direction: It's not working with yowsup either.
I guess I have to try another method to fetch my password then.

Will report back as soon as I figured out another method to obtain my password!

**Comment by JulianHH** [comment]
Case closed! :)

I downgraded my android to 4.4.4 as the password extractor isn't working on lollipop I guess.
It's working as expected now. Thumbs up! :)
