### ISSUE TITLE
Disconnection event

### ISSUE THREAD

**Issue by bitimp** [hidespb/node-whatsapi#59]
Hi! Is there an event of disconnect? I can't found. 

I really appreciate any help you can provide.

**Comment by tvandergeer** [comment]
Yes, it’s either “end” or “reconnect”. It issues “reconnect” when config.reconnect = true and “end” when this value is false. See [here](https://github.com/hidespb/node-whatsapi/blob/master/whatsapi.js#L338) for more info.
