### ISSUE TITLE
Support for broadcast lists?

### ISSUE THREAD

**Issue by JulianHH** [hidespb/node-whatsapi#62]
Hi there!

Is support for broadcast lists planned?

This is what I'd need right now :)

Best,
Julian

PS: Keep up the great work!

**Comment by matteocontrini** [comment]
Not planned and never will be.
Too risky for unwanted spam.

**Comment by JulianHH** [comment]
Ok, thanks for clarifying!

**Comment by russellwmy** [comment]
I think whatsapp prefer developer implement broadcast.
The  concept of  broadcast is  you send message to people who have you in their contact list.
It would not be banned.

**Comment by JulianHH** [comment]
Yeah, thinkin' the same.

Anyway, there are other libraries which already have that feature implemented. You can use that source code and adapt it to nodejs. That's what I'm doing right now.

**Comment by matteocontrini** [comment]
The problem here is another: the risk of unwanted spam.
