### ISSUE TITLE
Messages to Group?

### ISSUE THREAD

**Issue by JulianHH** [hidespb/node-whatsapi#63]
Hi there,

sorry, got to ask again:
How to send a message (/image/...) to a group?

Thanks and best,
Julian

**Comment by matteocontrini** [comment]
The same `sendMessage` function, documented [here](https://github.com/hidespb/node-whatsapi/wiki/Sending-messages)

**Comment by JulianHH** [comment]
Gosh, you are fast.. :+1: 

Thanks!

**Comment by matteocontrini** [comment]
:wink:
