### ISSUE TITLE
isGroup only defined upon receipt regular text message

### ISSUE THREAD

**Issue by timbersoen** [hidespb/node-whatsapi#65]
Hi there!

The "isGroup" property is only set upon receipt of regular text messages, video, audio etc messages do not contain this property (so i had to determine the value of this property for these type of messages manually), is there a reason for this? 

Thanks for your response:)

**Comment by matteocontrini** [comment]
2059bcf6650313550b13aabfa356d5d48d842c36

It should work in this way. If you can test it cloning the repository, I'll publish the update to npm.

**Comment by matteocontrini** [comment]
[Released](https://github.com/hidespb/node-whatsapi/releases/tag/v1.1.1)
