### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by jasaap** [hidespb/node-whatsapi#66]
What creates the endless loop after running wa.connect() function? Everything works as expected, but from the moment I run that function, the script never terminates, unless I do a wa.disconnect(). Where is this endless loop coming from?

**Comment by matteocontrini** [comment]
The endless loop is [here](https://github.com/hidespb/node-whatsapi/blob/master/whatsapi.js#L348) and it is there because we want to read the incoming nodes on the socket, don't we?

Without that loop, nothing would work apart from connection.
