### ISSUE TITLE
Send receipt at custom time

### ISSUE THREAD

**Issue by timbersoen** [hidespb/node-whatsapi#68]
Hi guys,

Is it possible to send the receipt node when we actually read the incoming message, instead of sending the receipt message automatically (just like the native app)? I would like to use a simple database to track which message / nodes are read (by an human being) and which are not. 

Thanks for your response, keep up the good work:)!

**Comment by matteocontrini** [comment]
Hi,
`sendReceipt` option is there in the [WhatsApiConfig](https://github.com/hidespb/node-whatsapi/wiki/API-Reference#WhatsApiConfig)

**Comment by matteocontrini** [comment]
Well wait, but you can't send the read receipt after that. I'll check how to provide that.

**Comment by matteocontrini** [comment]
[Done](https://github.com/hidespb/node-whatsapi/releases/tag/v1.3.0)

**Comment by timbersoen** [comment]
Thanks a lot, this is great!!!
