### ISSUE TITLE
processGroupNotification

### ISSUE THREAD

**Issue by timbersoen** [hidespb/node-whatsapi#69]
Hi Guys,

processNode.js contains a little typo, on line: 656: processGroupNotification(node, nodeId); is called, this triggers an exception because this function "doesnt exists", this line should be: this.processGroupNotification(node, nodeId); (note the "this.") I thought, i let you know:)

**Comment by matteocontrini** [comment]
Sorry - haven't got time to test it :|
If you make a pull request I can approve it now.

**Comment by timbersoen** [comment]
I cannot push my branch to this repo, what am i doing wrong? It keeps returning the following error: 
> git push origin processGroupNotification
> remote: Permission to hidespb/node-whatsapi.git denied to timbersoen.

**Comment by matteocontrini** [comment]
Fork on GitHub. Clone the new repo. Push changes. Create a pull request on GitHub
