### ISSUE TITLE
sendMessageReceipt doesnt seem to work

### ISSUE THREAD

**Issue by timbersoen** [hidespb/node-whatsapi#72]
Hi Guys,

I cant get the new sendMessageReceipt function to work. I provide the right parameters (from & message id), but nothing happens, no receipt is send.

Even later whatsapp closes the connection giving the following error:
rx <stream:error>
rx   <ack></ack>
rx </stream:error>

 Does anyone else has this problem?

**Comment by matteocontrini** [comment]
Patched. The node was created but not sent. The function prefix is `send` so you would expect it to send the node as well.

**Comment by timbersoen** [comment]
Thanks matteocontrini:)
