### ISSUE TITLE
{ code: '501', message: 'feature-not-implemented' } error while syncing contacts

### ISSUE THREAD

**Issue by timbersoen** [hidespb/node-whatsapi#74]
Hi Guys,

While syncing my contacts i sometimes get this error:
{ code: '501', message: 'feature-not-implemented' }

I sync contacts in batches of 10 numbers foreach batch, this batch runs every 60 seconds until all contacts are synced (i keep track of those within a database). While some phone numbers synced fine, others gave me this strange exception.

I`m using a "interactive delta" sync for this process (see below), what am i doing wrong?

wa.requestContactsSync([arrayOfJids], 'delta', 'interactive', function (e, r) {})

Hope to hear from you soon:)

**Comment by tvandergeer** [comment]
Can you send an (anonymized) debug log of a message that failed? And the response/error? It probably also responds with a "backoff" value (in seconds) to tell you that you should try again later. It's a way of telling you that you're syncing too often.

**Comment by timbersoen** [comment]
Thanks for your response. Is it possible to add this back-off value (in seconds) to the "error" object of the requestContactsSync callback? This way we are able to take this value into account & maybe prevent future errors like this one "{ code: '501', message: 'feature-not-implemented' }". 

Unfortunately, i can not send you any more detailed logs, there weren't enabled at the time the error occurred, i only have the value of the error object from the requestContactsSync callback.

Are there any guidelines to this sync process? Like:
- Maximum contacts to sync foreach sync request
- Minimum time between sync processes

Thanks in advance for your response!

**Comment by matteocontrini** [comment]
Added backoff time to the latest [release](https://github.com/hidespb/node-whatsapi/releases/tag/v1.3.3). Handle it :)
