### ISSUE TITLE
Whatsapi Singleton

### ISSUE THREAD

**Issue by brunocascio** [hidespb/node-whatsapi#75]
They plan to use the singleton pattern for instantiate the api?

**Comment by matteocontrini** [comment]
Why singleton? We give users the ability to create as many instances as they want

**Comment by brunocascio** [comment]
I think that a developer will use just only instance of the api for your app-client in runtime. Multiple clients is equal to multiple instance of these app-client.

**Comment by matteocontrini** [comment]
And why should we change the pattern if it's good now? If a developer wants to create more than one instance, he can. If he doesn't need more instances, he creates just one of them.

**Comment by brunocascio** [comment]
It's ok... anyway if an user need just only instance should implement the singleton pattern. (e.g angularJS client)

**Comment by matteocontrini** [comment]
If you need that, you can wrap the whatsapi module in a sub-module of your application so that only one instance can exist

**Comment by brunocascio** [comment]
Yes, i already implemented :)

Thanks @matteocontrini :+1:
