### ISSUE TITLE
Contact Sync Question...

### ISSUE THREAD

**Issue by raajamalik** [hidespb/node-whatsapi#76]
Hello,

While syncing contacts we have pass phone number. Is there any api, with which we an get all of my contacts from whats app. I see that there is one for group, with which we can get all the groups and then on we can loop through all the groups to find members of that group.

Is this production ready?
Thanks
Raja

**Comment by raajamalik** [comment]
I also went through this. If there is no API for whatsapp, then how are you giving this API?

http://mashable.com/2015/03/25/whatsapp-developers-api/

**Comment by tvandergeer** [comment]
Node-whatsapi is a port of the great work done by the people behind WhatsAPI (more recently known as Chat-API) and Yowsup. They reverse engineered the WhatsApp protocol by decompiling the oFficial WhatsApp clients (Apps), sniffing network traffic and countless hours of trial and error. WhatsApp (the company) is not supporting or condoning these projects. They're even actively fighting these projects by taking legal steps and by blocking accounts of users.




WhatsApp does not provide any way of retrieving the contacts of an account that have previously been synced. It's not in the official client. The official App is only capable of retrieving contacts and message history by using the backup restore functionality. But that's not in scope of this project.
