### ISSUE TITLE
sendMessageReceipt still doesn't seem to work

### ISSUE THREAD

**Issue by timbersoen** [hidespb/node-whatsapi#77]
Hi Guys, 

The "sendMessageReceipt" function stil doesn`t seem to work. Within the file: extensions/service.js on line: 82 we see this line: this.sendNode(protocol.Node('receipt', attributes));

While debugging the "sendNode" function, i saw that the given node was undefined. 
I changed this row to:  this.sendNode(new protocol.Node('receipt', attributes)); (note the "new"). 
After this change, the given node was defined & send, but the receipt node still doesn't work (no blue checkmarks on my phone)

Please let me know if you need any more info to solve this problem. 

Thanks for you time:)

**Comment by tvandergeer** [comment]
Yes, you're right. The "new" is missing. I will correct that. Did you send both receipts? (as described [here](https://github.com/hidespb/node-whatsapi/wiki/Message-receipts))

**Comment by matteocontrini** [comment]
LOL, sorry for so many mistakes for such a simple function.

**Comment by matteocontrini** [comment]
Latest [release](https://github.com/hidespb/node-whatsapi/tree/v1.3.3) fixes this.
