### ISSUE TITLE
Break line on message send

### ISSUE THREAD

**Issue by webjoel** [hidespb/node-whatsapi#79]
It´s possible break the line on message send?

**Comment by matteocontrini** [comment]
Just send the line break character `\n`

**Comment by webjoel** [comment]
"\n" does not work in my case because I am doing a http get past the message as parameter, for solution used the "%0D%0A".

**Comment by matteocontrini** [comment]
That's not related to the module.
The right and working way is:

```js
wa.sendMessage(number, 'First line\nSecond line');
```

**Comment by webjoel** [comment]
Perfect! The problem not is api, is my case of send message, because http convert caracter another caracter on http get param text.

**Comment by webjoel** [comment]
It´s resolved! Thank you!

**Comment by matteocontrini** [comment]
Consider POST request for that kind of things!

**Comment by webjoel** [comment]
Yes, http get it´s test only. ;)
