### ISSUE TITLE
Not able to send a fixed message from sendMessage

### ISSUE THREAD

**Issue by zextr** [hidespb/node-whatsapi#80]
India (/ˈɪndiə/), officially the Republic of India (Bhārat Gaṇarājya), is a country in South Asia. It is the seventh-largest country by area, the second-most populous country with over 1.2 billion people, and the most populous democracy in the world.

I am not able to send above mentioned message by using sendMessage method. However I am able to send subset or superset of this message.

**Comment by matteocontrini** [comment]
This is #41
