### ISSUE TITLE
No routes error

### ISSUE THREAD

**Issue by febryantonius** [hidespb/node-whatsapi#83]
Hi, I am getting no_routes error when trying to call codeRequest function on whatsapiregistation.

Help me please

**Comment by matteocontrini** [comment]
Virtual number?

**Comment by febryantonius** [comment]
No, I am using my phone number

**Comment by matteocontrini** [comment]
For catching errors:
```js
wa.on('error', function(err) {
  // log and restart
});
```

For the number, have you tried registering it with another method? A real phone for example, or yowsup?

**Comment by febryantonius** [comment]
I just tried to register it with yowsup and it still returns no_routes error. I tried to use phone and it works so I assume my server's IP is blocked by Whatsapp

**Comment by matteocontrini** [comment]
Usually not an IP issue. Are you using correct MNC and MCC codes?

**Comment by febryantonius** [comment]
Yes. I didn't modify MCC and MNC code generated in codeRequest. I have tried registering the number in my local and it worked. This error only happens when I registered the number in my server.

**Comment by matteocontrini** [comment]
You need to set the right MNC and MCC codes, it certainly won't work if you don't set them.

MCC: https://it.wikipedia.org/wiki/Mobile_Country_Code
MNC: http://www.mcc-mnc.com/ and other resources on Internet

**Comment by febryantonius** [comment]
So I should provide the MNC code according to what my phone number's network? When I looked at the API, MNC code is provided from file countries.json in folder registration.
![screenshot from 2015-07-02 13 16 02](https://cloud.githubusercontent.com/assets/4846557/8470946/c0ad75da-20bc-11e5-9ab3-0aa91aaadd9b.png)

**Comment by matteocontrini** [comment]
The country code (MCC) is recognized with your phone number prefix.
The network core (MNC) depends on your mobile network, it can't be automatically chosen for you.

**Comment by febryantonius** [comment]
Okay, thank you for the information. I will fix my code and try it again

**Comment by febryantonius** [comment]
Hi matteo, I have tried to connect using right MNC and MCC code. I tried it several hours ago and it worked. But when I try it again now, it returns no_routes error again.

**Comment by matteocontrini** [comment]
Just use the MCC and MNC codes associated with your phone number. I can't say anything else. There's nothing to invent, just use the codes.
