### ISSUE TITLE
Not Spamming, No Robotic Replies, but number blocked

### ISSUE THREAD

**Issue by guns2410** [hidespb/node-whatsapi#84]
I am facing an issue here. One of my clients are getting the number blocked. I am following the exact protocol as mentioned in the WIKI.

The flow that i follow is:

1. Create Adapter
2. Connect()
3. On Connect - Login
4. On Login
 * sendIsOnline()
 * requestPrivacySettings()
 * requestServerProperties()
 * requestContactsSync()
   * For Each Contact sendPresenceSubscription(), getStatus() and getProfilePicture()

And when i receive a message:

1. `adapter.requestContactsSync('1234567890', 'delta', 'background');`
2. getProfilePicture()
3. Save to DB

Now, what we do and why do we use WhatsApi

We enable our existing Customers to talk to their internal teams on WhatsApp. So, a customer initates a chat and a help desk team responds to them on an application.

Got the number blocked now. Unable to understand where am i going wrong.

Also, the total number of messages exchanged between the customer and the helpdesk team is around 1k a day.

**Comment by tvandergeer** [comment]
Just a thought: are you sending delivery/read receipts when you receive a message and are you sending isTyping notifications prior to sending messages?

**Comment by guns2410** [comment]
Yes,  I do that. I send delivery notification once the server parses the message from sender and send a read receipt once the end user reads the message.  Just like the official whatsapp client.

**Comment by tvandergeer** [comment]
And what about the isTyping status before sending messages?

**Comment by matteocontrini** [comment]
And are you sending messages to more than one user at the same time? Do you have a queue for that?

**Comment by brunocascio** [comment]
Guys, this bulk operation really simulates the official app?
* requestContactsSync()
  ** For Each Contact sendPresenceSubscription(), getStatus() and getProfilePicture()`

**Comment by matteocontrini** [comment]
`getStatus` and `getProfilePicture` yes but only the very first time you launch the application.
Presence subscription is sent for all the contacts once, because it is preserved between sessions.

**Comment by brunocascio** [comment]
Ok :)

**Comment by guns2410** [comment]
The messages are not sent at one time. There is at least 2-3 seconds delay if two messages are sent by two different users. A blocking method is used to restrict sending of messages to different users at a time. Also, typing status is sent while the user types the messages and message is sent when pressed enter. So typing is sent exactly the same way as an official client.

**Comment by matteocontrini** [comment]
Maybe you're sending the typing state to more than one user at the same time. Probably the fact that a single number is used by more than one user is not ideal for WhatsApp

**Comment by guns2410** [comment]
The blocking mode used in sending a message is also used for typing state. Here is my code used for sending message and sending the typing state:

**Typing State**
> data.from is the users number
> global.waAdapter[data.from] is the copy of the WA Adapter created during the first login
> data.to is the end uses number

```javascript
if (global.blockSendTyping[data.from] == undefined) {
  global.blockSendTyping[data.from] = 'blocked';
  var wa                              = global.waAdapter[data.from];
  wa.sendComposingState(data.to);
  setTimeout(function () {
    setTimeout(function () { global.blockSendTyping[data.from] = undefined; }, 1000);
    wa.sendPausedState(data.to);
  }, 2000);
}
```

**sending of message**

```javascript
this.sendMessage = function (data) {

  if (global.blockSendMessage[data.from] == undefined) {
    global.blockSendMessage[data.from] = 'blocked';

    // initiating the global whatsapp adapter
    var wa = global.waAdapter[data.from];
    wa.sendMessage(data.to, data.message, null, function (err, id) {
      setTimeout(function () { global.blockSendMessage[data.from] = undefined; }, 1000);
      // save the message delivered timestamp
    });
  } else {
    var self = this;
    setTimeout(function () {self.sendMessage(data);}, 2000);
  }
};
```

**Comment by niravpatel2008** [comment]
Guys one que,

I am doing only sendIsOnline, requestContactsSync after login.
requestPrivacySettings, requestServerProperties are necessary ?

also i have added reconnect: true while creating object but still user gets offline after few hours, for that i have added one sh script which will restart server after 5 hr.

Please guide me if any thing required in flow.
I am not spamming, only replying on user query.

**Comment by guns2410** [comment]
yes @niravpatel2008, requestPrivacySettings and requestServerProperties are important if you want to immitate the official whatsapp client.

Also, if you do sendIsOnline only once your number would be online. I think you also send to send presence subscription to every contact for you to be online.

Hope this answers.

**Comment by guns2410** [comment]
@matteocontrini, hope the code that i have shared is correct and do not have a problem with the code for number getting blocked.

**Comment by matteocontrini** [comment]
@niravpatel2008 officially, they're used only once after the first login, or periodically but not at every login. (Officially, because there's nothing wrong doing it at every launch).

@guns2410 the reason of getting blocked doesn't have to be because you wrote wrong code. It could be a filter on the kind of messages you send or a report from someone about your number.
