### ISSUE TITLE
Handling receipts

### ISSUE THREAD

**Issue by humodev** [hidespb/node-whatsapi#90]
I'm trying to receive receipts events when a client reads my messages. 
So I have this code

```javascript
wa.on('clientReceived', function (args) {
	console.log("Client received " + args.id);
	updateMessage(args);
});
```

But I'm getting events triggers of messages that I already received the event triggered for. 

Is this a mistake in my code? Is there a way to tell whatsapp that I already saw this events or something like that? 

Thank you

**Comment by thiagupct** [comment]
Provide acks for events. Refer [this](https://github.com/hidespb/node-whatsapi/issues/43).

**Comment by humodev** [comment]
That did it, thank you very much!
