### ISSUE TITLE
unread message 

### ISSUE THREAD

**Issue by FouedM** [hidespb/node-whatsapi#93]
Hi , 
I'm trying to make a notification for unread message but unfortunately when I use "wa.sendMessageReceipt(message);" it doesn't work , I tried to write in the console anything when I receive a message but there was no result , in whatsapi.config the " sendReceipt = 2 " and when I received a message i got in my console : 

```
rx <ack from="mynumber@s.whatsapp.net" class="message" id="message-1439545756-1" t="1439545755"></ack>
Server received message message-1439545756-1

rx <receipt from="mynumber@s.whatsapp.net" type="read" id="message-1439545756-1" t="1439545756"></receipt>

tx <ack to="mynumber@s.whatsapp.net" class="receipt" id="message-1439545756-1" type="read"></ack>
```

please can any one help me , or give me an example how to do it , and thank you for this great API
Keep the good work ON!

**Comment by matteocontrini** [comment]
The debug output you posted is not related to a received message, if I remember correctly.
Have you read [here](https://github.com/hidespb/node-whatsapi/wiki/Message-receipts) about receipts?

**Comment by FouedM** [comment]
So it's about what ? I just want to show anything in my terminal when i receive a message, I tried with putting the receipts function in different place in the code but it didn't work , every thing else work perfectly ,that code is just bellow the message in my console. please if you don't understand my question let me know .
Thank you so much for your speedy reply.

**Comment by matteocontrini** [comment]
I don't get what you want to do. Do you want to read incoming messages?

**Comment by FouedM** [comment]
No , I'm using the nodejsapi to build something similar to the real app with UI .
it's possible to receive many message in the same time from different numbers , I want to show a notification when there is new messages for example in My contacts list I have three contacts A,B,C and while I'm chatting with A , B sends a message so it want to show a notification that there is a new message from B , there is a way to make it with the api or I should find other solution ?

**Comment by matteocontrini** [comment]
The way you use node-whatsapi is not an issue of this repository. We provide functions and events, which are documented in the [guide](https://github.com/hidespb/node-whatsapi/wiki/Documentation-guide-(v1)) and in the [reference](https://github.com/hidespb/node-whatsapi/wiki/API-Reference).

For example, you receive messages in your code as explained [here](https://github.com/hidespb/node-whatsapi/wiki/Receiving-messages). The way you decide to display the message in your UI or to the user of your application is completely off-topic here.
