### ISSUE TITLE
setProfilePicture

### ISSUE THREAD

**Issue by mobilefirst** [hidespb/node-whatsapi#95]
I like to set the profile picture with the command 
wa.setProfilePicture('xxxx.jpeg', function(err, id) { 
})

But i always get an error { code: '406', message: 'not-acceptable' }

**Comment by matteocontrini** [comment]
Are you having the issue with all the images or one in particular?
That function still hasn't be checked after WAUTH-2 if I remember correctly.

**Comment by mobilefirst** [comment]
i tried various kind of jpg images but always get an error { code: '406', message: 'not-acceptable' }

**Comment by AminaG** [comment]
+1. Cannot setProfileImage with any file

**Comment by AminaG** [comment]
I solved it by upload a file exactly 400x400 pixels!

**Comment by mobilefirst** [comment]
i tried 350 x 350, 400 x 400 and 450 x 450 pixels. I also tried with fileextension *.jpg and jpeg but none of my tries work well. i always get { code: '406', message: 'not-acceptable' }

**Comment by AminaG** [comment]
What file size are you using?
Did you tried low quality files?
בתאריך 21 באוג 2015 07:43, "Jürgen Schaar" <notifications@github.com> כתב:

**Comment by mobilefirst** [comment]
yes, i tried from 4k up to 64k different file sizes but still get { code: '406', message: 'not-acceptable' }

**Comment by tvandergeer** [comment]
Can you share your code? I will dig up what I used to test this feature when we built it and see what it does...




Best regards,




Tom

**Comment by tvandergeer** [comment]
This is what I do:
```
wa.setProfilePicture('http://lorempixel.com/400/400/?.jpg', function(){});
```
NB. The "?.jpg" is just there to trick the downloader in node-whatsapi to treat it as JPEG image.

If this it not working for you either, please send us the debug traces. On what platform are you running this?

**Comment by mobilefirst** [comment]
Thanks,

your sample is working well. If i download an image from http://lorempixel.com/400/400/?.jpg and store is on my local machine it works also. As a result there is something wrong with my images but i have no idea what. Any suggestion about the requirements of the pic ?

**Comment by tvandergeer** [comment]
Are you sure you are using JPEG and are you using the correct dimension? Can you post an image that is not working?

**Comment by mobilefirst** [comment]
I found the problem. The jpeg must have a max quality of 80%. Now everything works fine.

Thank you all for supporting me

**Comment by matteocontrini** [comment]
Thanks for sharing.

**Comment by AminaG** [comment]
What i said in the beginning. Check the quality of the files...
בתאריך 22 באוג 2015 11:48, "Jürgen Schaar" <notifications@github.com> כתב:
