### ISSUE TITLE
How to send Smiley and emoticons? 

### ISSUE THREAD

**Issue by AminaG** [hidespb/node-whatsapi#96]
I tried /xHexCode
I Tries \uHexCode

Nothing works.

anyone have an idea? (An example of one emoticons?)

**Comment by matteocontrini** [comment]
Hi,
I recommend that you use [this](https://www.npmjs.com/package/node-emoji) NPM module, which simplifies everything.

Example usage:
```js
var heart = emoji.get(':heart:');
// or
var heart = emoji.get('heart');
// or with a message
var message = 'I :heart: node-whatsapi';
var emojified = emoji.emojify(message);
```
